spring:
  application:
    name: technical_test
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=technical_test;createDatabaseIfNotExist=true;encrypt=true;trustServerCertificate=true;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: yourStrong(!)Password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.SQLServerDialect
logging:
    level:
      root: INFO




